import './style.css';
import { journeys } from './data.js';
const app=document.querySelector('#app');
const stored=()=>{try{return JSON.parse(localStorage.getItem('ghats-drafts')||'[]')}catch{return []}};
let filter='All', modal=null;
const images={ridge:'/assets/ridgeline.png',forest:'/assets/forest.png'};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const all=()=>[...stored(),...journeys];
const link=id=>`#story/${encodeURIComponent(id)}`;
const thumb=(j,cl='')=>`<img class="${cl}" src="${images[j.image]||images.forest}" alt="Illustrative landscape image, not a documentary photograph of this walk" loading="lazy" style="object-position:${j.position||'center'}">`;
function shell(inner){return `<div class="site-shell"><header class="masthead"><a class="brand" href="#home" aria-label="Ghats fieldnotes home"><span class="brand-mark">G<span class="brand-slash">/</span>F</span><span class="brand-text">GHATS<br>FIELDNOTES</span></a><nav aria-label="Main navigation"><a href="#home" data-nav="home">Overview</a><a href="#journal" data-nav="journal">The journal</a><a href="#about" data-nav="about">About</a></nav><button class="nav-write" id="write-top" type="button">+ New fieldnote</button></header>${inner}<footer><span>G / F &nbsp; © 2026</span><span>Illustrative imagery and demo stories, awaiting real trails.</span><a href="#home">Back to the beginning ↑</a></footer></div>${modal?modalMarkup():''}`}
function home(){const latest=all();return shell(`<main><section class="hero"><div class="hero-image" role="img" aria-label="Illustrative panoramic mountain ridgeline at sunrise"></div><div class="hero-shade"></div><div class="hero-content"><span class="eyebrow light">A JOURNAL OF WALKS & WEATHER &nbsp; / &nbsp; 01—03</span><h1>For the long<br><em>way home.</em></h1><p>Fieldnotes from the Western Ghats. A place for the trails, the weather, and everything in between.</p><a class="hero-link" href="#journal">Explore the journal <span>↗</span></a></div><div class="hero-bottom"><span>WESTERN GHATS / INDIA</span><span>SCROLL TO WANDER ↓</span></div></section><div class="disclosure"><span class="asterisk">✳</span><span>This is a preview journal: stories and route figures below are examples, not records of Aditya's treks. Images are illustrative.</span></div><section class="intro section-pad"><div class="section-index">01 / IN THE FIELD</div><div class="intro-copy"><h2>Out there, the days<br>feel <i>different.</i></h2><p>A walking archive for the mornings that begin before sunrise and the trails that refuse to be rushed. Not a list of summits. A record of the small things worth remembering.</p><a class="text-link" href="#about">The idea behind this journal <span>↗</span></a></div></section><section class="feature"><div class="feature-copy"><span class="eyebrow">FEATURED FIELDNOTE / DEMO</span><div><span class="feature-num">NO. 001</span><h2>${safe(latest[0].title)}</h2><p>${safe(latest[0].intro)}</p><a class="round-arrow" href="${link(latest[0].id)}" aria-label="Read ${safe(latest[0].title)}">↗</a></div><span class="feature-bottom">${safe(latest[0].date)} &nbsp; • &nbsp; ${safe(latest[0].region)}</span></div><div class="feature-photo">${thumb(latest[0])}<span>ILLUSTRATIVE IMAGE / NOT A TRAIL RECORD</span></div></section><section class="journal-preview section-pad"><div class="section-head"><div><div class="section-index">02 / THE JOURNAL</div><h2>A few things<br>from the trail.</h2></div><a class="text-link" href="#journal">All fieldnotes <span>↗</span></a></div><div class="cards">${latest.slice(0,3).map((j,i)=>card(j,i)).join('')}</div></section><section class="quote"><span>FIELD NOTE NO. 00</span><p>There is no hurry<br>in the hills.</p><a href="#journal">TAKE A LOOK AROUND ↗</a></section></main>`)}
function card(j,i){return `<a class="story-card" href="${link(j.id)}"><div class="card-image">${thumb(j)}<span class="card-index">${String(i+1).padStart(2,'0')}</span></div><div class="card-meta">${safe(j.category).toUpperCase()} <span>${safe(j.date)}</span></div><h3>${safe(j.title)} <span>↗</span></h3><p>${safe(j.intro)}</p></a>`}
function journal(){let list=all().filter(x=>filter==='All'||x.category===filter);return shell(`<main class="listing"><div class="listing-top section-pad"><span class="eyebrow">INDEX / THE JOURNAL</span><h1>Collected<br><em>fieldnotes.</em></h1><div class="listing-desc"><p>Little records of getting out there. Browse by mood, then stay for a story.</p><span>All entries are samples unless you add your own local draft.</span></div></div><section class="listing-body section-pad"><div class="filter-row" role="group" aria-label="Filter fieldnotes">${['All','Rain walks','Ridge days','My drafts'].map(f=>`<button class="filter ${f===filter?'selected':''}" data-filter="${f}" aria-pressed="${f===filter}">${f} <span>${f==='All'?all().length:f==='My drafts'?stored().length:all().filter(j=>j.category===f).length}</span></button>`).join('')}</div>${list.length?`<div class="cards listing-cards">${list.map(card).join('')}</div>`:`<div class="empty"><h2>Nothing here yet.</h2><p>Start a note and give this section a story.</p><button id="empty-write">Write a fieldnote ↗</button></div>`}</section></main>`)}
function story(j){return shell(`<main class="story"><div class="story-header section-pad"><a class="back" href="#journal">← ALL FIELDNOTES</a><span class="eyebrow">${safe(j.region)} / ${safe(j.date)}</span><h1>${safe(j.title)}<span class="title-dot">.</span></h1><p>${safe(j.intro)}</p><div class="story-stats"><div><span>DISTANCE</span><strong>${safe(j.distance)} <small>km</small></strong></div><div><span>ASCENT</span><strong>${safe(j.climb)} <small>m</small></strong></div><div><span>TIME OUT</span><strong>${safe(j.time)}</strong></div><div><span>STATUS</span><strong class="demo-flag">${j.draft?'LOCAL DRAFT':'DEMO ENTRY'}</strong></div></div></div><div class="story-visual">${thumb(j)}<span>ILLUSTRATIVE IMAGE / REPLACE WITH YOUR OWN PHOTOGRAPH</span></div><div class="story-body"><aside><span>FIELDNOTES / ${safe(j.category.toUpperCase())}</span><div>↘</div></aside><article><p class="lead">${safe(j.intro)}</p>${j.sections.map(([head,body])=>`<section><h2>${safe(head)}</h2><p>${safe(body)}</p></section>`).join('')}<div class="story-note"><span>✳ A NOTE ON THIS ENTRY</span><p>${safe(j.note)}</p></div></article></div><div class="next-story section-pad"><span>KEEP WALKING</span><a href="${link(all()[(all().findIndex(x=>x.id===j.id)+1)%all().length].id)}">Next fieldnote <span>↗</span></a></div></main>`)}
function about(){return shell(`<main class="about-page"><section class="about-top section-pad"><span class="eyebrow">ABOUT THE ARCHIVE / 2026</span><h1>Keep the dust.<br><em>Keep the details.</em></h1><p>A personal home for trekking stories, photographs, and the parts of a day the route data cannot hold.</p></section><div class="about-grid"><div>${thumb(journeys[0])}</div><div><span class="section-index">THE INTENTION</span><h2>A map can tell you where. A journal remembers why.</h2><p>This site is designed as an empty notebook with an example of what it could become. Replace the demo stories with your own walks, the illustrative images with your photographs, and the example route numbers with measured data.</p><p>Nothing here asserts that a trek happened. The design is ready when the real stories are.</p><button class="dark-button" id="about-write">Add a local draft ↗</button></div></div><section class="about-closing section-pad"><span>01 / WALK</span><span>02 / NOTICE</span><span>03 / REMEMBER</span></section></main>`)}
function modalMarkup(){return `<div class="modal-backdrop" id="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" id="modal-close" aria-label="Close">×</button><span class="eyebrow">YOUR OWN WORDS / LOCAL ONLY</span><h2 id="modal-title">New fieldnote.</h2><p>This saves to this browser only. It won't publish, sync, or send anything.</p><form id="note-form"><label>Title<input name="title" maxlength="64" required placeholder="A day worth keeping"></label><div class="form-grid"><label>Date<input name="date" type="date" required></label><label>Kind<select name="category"><option>Rain walks</option><option>Ridge days</option></select></label></div><label>Opening line<input name="intro" maxlength="190" required placeholder="It began with... "></label><label>The story<textarea name="story" rows="5" required placeholder="Write what you want to remember."></textarea></label><button class="dark-button" type="submit">Save local draft ↗</button></form></div></div>`}
function render(){let hash=decodeURIComponent(location.hash.slice(1)||'home');let id=hash.startsWith('story/')?hash.slice(6):null;let j=id&&all().find(x=>x.id===id);app.innerHTML=j?story(j):hash==='journal'?journal():hash==='about'?about():home();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(id?'journal':hash)));bind();window.scrollTo({top:0,behavior:'instant'})}
function bind(){document.querySelectorAll('#write-top,#about-write,#empty-write').forEach(b=>b?.addEventListener('click',openModal));document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;render()}));document.querySelector('#modal-close')?.addEventListener('click',closeModal);document.querySelector('#modal-backdrop')?.addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal()});document.querySelector('#note-form')?.addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target);let title=String(d.get('title')).trim(),intro=String(d.get('intro')).trim(),body=String(d.get('story')).trim();if(!title||!intro||!body)return;let j={id:'draft-'+Date.now(),title,date:d.get('date'),category:d.get('category'),intro,distance:'—',climb:'—',time:'—',region:'YOUR NOTE / LOCAL',image:'forest',sections:[['01 / Your story',body]],note:'This is your locally saved draft. It only lives in this browser.',draft:true};localStorage.setItem('ghats-drafts',JSON.stringify([j,...stored()]));modal=null;location.hash=link(j.id);render()})}
function openModal(){modal=true;app.innerHTML=app.innerHTML.split('<div class="modal-backdrop"')[0]+modalMarkup();bind();document.querySelector('#modal-close').focus();document.body.style.overflow='hidden'}
function closeModal(){modal=null;document.querySelector('#modal-backdrop')?.remove();document.body.style.overflow=''}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal)closeModal()});window.addEventListener('hashchange',()=>{modal=null;document.body.style.overflow='';render()});render();
